apiVersion: v1
kind: ClusterRole
metadata:
  name: router-reader
rules:
- apiGroups:
  - ""
#  - route.openshift.io
  attributeRestrictions: null
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
